### PR TITLE
S24FUJI-24: Front-End: Add New Inventory Item Component (Responsive)

### PR DESCRIPTION
**Pull request by Michelle-Watson**
[Feature s24 fuji 24 mw
](https://brainstationeducation.atlassian.net/browse/S24FUJI-24)

The user must be able to click the “+ Add New Item” button and have that functionality lead to a form where the user can input the necessary data. The successfully added item should appear immediately in the list of inventory. 

Ensure this component works at and between all breakpoints and is fully responsive without any elements overlapping.

Assign the equivalent back-end ticket as well, as it will be easier if a given team member does both the front end and back-end task for this workflow.

Please note that the ‘Quantity’ field is dynamic. This means that if the ‘Status’ has been defined as “Out of Stock” the ‘Quantity’ field will not be visible. Conversely, if the ‘Status’ has been set to “In Stock” the ‘Quantity’ field will be visible, and the user should be able to enter the correct number for the item’s quantity.

The Figma prototype shows examples of “In Stock” functionality on the Add New Inventory Item page and “Out of Stock” functionality on the Edit Inventory Item page. This functionality needs to work identically on Add and Edit pages.

All form fields need to have validation both on Front-End and Back-End. All fields are required (non-empty). Front-End validation needs to be custom and cannot use default HTML5 form validation.

-=-=-=-=-=---=

Reused Betty's logic, edit item is almost working, but clicking 'Update' doesn't work because the request doesn't populate with the warehouse_id needed in the request (which is needed for the PUT/EDIT request) @nicolette-cheng

### CODE REVIEW

**Review by betty-alemayehu — CHANGES_REQUESTED** [review]
LGTM! Latest push solves the missing warehouse id issue. 
Pending asks:

- [x] remove console logs
- [x] update BEM/naming from warehouse to inventory in .jsx and .scss

**Comment by Michelle-Watson** [comment]
@betty-alemayehu 
I was contemplating renaming all the warehouse -> inventory, but then I can't refuse your scss making our code a bit redundant, I imported your warehouse scss, and added a few extra tweaks for radio buttons and dropdowns. I'm very down to rename for bem though

Let me know if you still want me to copy paste your scss and change the names

I will remove console logs and tweak my added classnames that aren't BEM conforming

**Comment by Michelle-Watson** [comment]
@betty-alemayehu I've copied your .scss into mine and changed all the `warehouse-` into `inventory-`, I also changed some BEM classnames to not use -- if it's not a modifier (ex. `--link` -> `-link`)

**Comment by nicolette-cheng** [comment]
LGTM - all requested changes have been resolved. Tested S24FUJI-22 requirements for editing inv item as well, no issues here. Good to clear PR and merge.

**Pull request merged**
