### PR TITLE
S24FUJI-17: Front-End: Add new warehouse Component (Responsive) [WIP]

### PR DESCRIPTION
**Pull request by betty-alemayehu**
Initiated work on [ticket # [S24FUJI-17](https://brainstationeducation.atlassian.net/browse/S24FUJI-17)](https://brainstationeducation.atlassian.net/browse/S24FUJI-17?atlOrigin=eyJpIjoiMDcxNzJjY2RmODY1NGNkYjg0YTQxZmNkZjZlMzUyZWQiLCJwIjoiaiJ9) that:
- added logo and icon folders + assets to public folder
- created components for input fields and buttons, now refactored into styles within global scss
- created first draft of edit/delete form re ticket requirements

To do:

- [ ] input field validation
- [ ] incorporate header/footer
- [ ] full page design across devices (responsiveness)
- [ ] links/navigation plus server connections

### CODE REVIEW

**Comment by sept-17-bstn** [comment]
Use in <WarehouseAdd>
get rid of fragment
line 25ish:  src="/public/assets/icons/arrow_back-24px.svg"

**Comment by Michelle-Watson** [comment]
image
Files in the public directory are served at the root path.
Instead of /public/assets/icons/arrow_back-24px.svg, use /assets/icons/arrow_back-24px.svg. (x3)

**Comment by Michelle-Watson** [comment]
http://localhost:5173/warehouses/add
http://localhost:5173/warehouses/1/edit
Both lead to following page:
image

I entered info and clicked Add and the URL is now:
[http://localhost:5173/warehouses/add?warehouseName=fgoadifngaodfg&streetAddress=sfg[…]me=aerga&position=aergfdg&phoneNumber=adfgadfg&email=adfgadfg](http://localhost:5173/warehouses/add?warehouseName=fgoadifngaodfg&streetAddress=sfgdhsdfgh&city=&country=aergaerg&contactName=aerga&position=aergfdg&phoneNumber=adfgadfg&email=adfgadfg)

LGTM so far!

**Comment by Michelle-Watson** [comment]
Work will be continued in another PR, merging so we have access to styles.

Future:
Have Warehouse Details NEXT to Contact details (tablet+ responsiveness). Currently just the mobile design

Other todos will be pasted into the new PR:

- [ ]  input field validation
- [ ]  incorporate header/footer
- [ ]  full page design across devices (responsiveness)
- [ ]  links/navigation plus server connections

**Comment by Michelle-Watson** [comment]
LGTM!

**Pull request merged**
